//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tdtWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CprNumber
    {
        public int CprNumId { get; set; }
        public string Environment { get; set; }
        public string CprNummer { get; set; }
        public string UsedBy { get; set; }
    }
}
