// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Foobar" file="Settings.Designer.cs">
//   2015
// </copyright>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------
namespace OvidDemo.Properties
{
    using System.CodeDom.Compiler;
    using System.Configuration;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// The settings.
    /// </summary>
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        /// <summary>
        /// The default instance.
        /// </summary>
        private static Settings defaultInstance = (Settings)(Synchronized(new Settings()));

        /// <summary>
        /// Gets the default.
        /// </summary>
        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
