//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stf.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stf.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_done {
            get {
                object obj = ResourceManager.GetObject("icon_done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_eye {
            get {
                object obj = ResourceManager.GetObject("icon_eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_fail {
            get {
                object obj = ResourceManager.GetObject("icon_fail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_right_arrow {
            get {
                object obj = ResourceManager.GetObject("icon_right_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_star {
            get {
                object obj = ResourceManager.GetObject("icon_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var lastAnchor = &quot;&quot;;
        ///
        ////* Hide buttons if no messages are present - good idea, not implemented fully yet */
        ///var PassCount = 1;
        ///var FailCount = 1;
        ///var ErrorCount = 1;
        ///var WarnCount = 1;
        ///var InfoCount = 1;
        ///var DebugCount = 1;
        ///var TraceCount = 1;
        ///var InternalCount = 1;
        ///
        ///function getURLParameter(name) {
        ///    return decodeURIComponent((new RegExp(&quot;[?|&amp;]&quot; + name + &quot;=&quot; + &quot;([^&amp;;]+?)(&amp;|#|;|$)&quot;).exec(location.search) || [, &quot;&quot;])[1].replace(/\+/g, &quot;%20&quot;)) || null;
        ///}
        ///
        ///function toggleKeyValues() {
        ///    if ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap middot {
            get {
                object obj = ResourceManager.GetObject("middot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body onload=&quot;loadKeyValueList()&quot;&gt;
        ///	&lt;div id=&quot;header&quot;&gt;
        ///        &lt;aside&gt;
        ///            &lt;div id=&quot;logo&quot; style=&quot;float: right&quot;&gt;Ovid&lt;/div&gt;
        ///        &lt;/aside&gt;
        ///		&lt;h1 id=&quot;logtitle&quot;&gt;LOGFILETITLE&lt;/h1&gt;
        ///		&lt;p id=&quot;generatedbyOvid&quot;&gt;Leveret til dig af Ovid&lt;/p&gt;
        ///		&lt;div id=&quot;buttons&quot;&gt;
        ///			&lt;button id=&quot;passBtn&quot;          value=&quot;Hide&quot; type=&quot;button&quot; onclick=&quot;toggleLogElements(&apos;.pass&apos;,  &apos;passBtn&apos;,  &apos;Pass&apos;)&quot; &gt;Hide Pass&lt;/button&gt;
        ///			&lt;button id=&quot;failBtn&quot;          value=&quot;Hide&quot; type=&quot;button&quot; onclick=&quot;toggleLogElements(&apos;.fail&apos;,  &apos;failBtn&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenBody {
            get {
                return ResourceManager.GetString("OpenBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    font-family: verdana;
        ///    font-size: 1.0em;
        ///    color: black;
        ///    padding: 0;
        ///    margin: 0;
        ///}
        ///
        ///h1#logtitle {
        ///    font-size: 1.5em;
        ///    margin-bottom: 0;
        ///    padding-bottom: 0;
        ///}
        ///
        ///div#logo {
        ///    margin-right: 25px;
        ///    margin-left: 15px;
        ///    height: 150px;
        ///    width: 150px;
        ///    background: url(&apos;data:image/x-png;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxQTEhUUExQWFhUWGBsYGBgYGBwfGhoYFx0aFxgYGx0bHiggHRolHBoYIjEiJSkrLi4uGh8zODMtNyguLisBCgoKDQ0MDwwMDiwZFBksKzcsKyssKys3KysrLCssKy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/table&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SummaryLoggerFooter {
            get {
                return ResourceManager.GetString("SummaryLoggerFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;SummaryLogger for DatadrivenLoggerTest&lt;/title&gt;
        ///    &lt;style&gt;
        ///        #RunStats {
        ///            font-family: &quot;Trebuchet MS&quot;, Arial, Helvetica, sans-serif;
        ///            text-align: center;
        ///            width: 25%;
        ///            border-collapse: collapse;
        ///        }
        ///
        ///            #RunStats td, #RunStats th {
        ///                font-size: 1em;
        ///                border: 1px solid #98bf21;
        ///                padding: 3px 7px 2px 7px;
        ///            }
        ///
        ///            #RunStats th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SummaryLoggerHeader {
            get {
                return ResourceManager.GetString("SummaryLoggerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Transparent {
            get {
                object obj = ResourceManager.GetObject("Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
